apiVersion: v1
kind: Pod
metadata:
  name: redis-storage-ishay
  labels:
    name: redis-storage-ishay
spec:
  containers:
  - name: redis-storage-ishay
    image: redis:alpine
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /data/redis
        name: data
  volumes:
  - name: data
    emptyDir: {}
