apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    env:
      - name: SECRET_KEY
        valueFrom:
          configMapKeyRef:
            name: keyvalcfgmap
            key: config.txt
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
